baseURL = "https://dbalette-ai-finance.netlify.app"
languageCode = "en-us"
title = "My Portfolio"
theme = "ananke"

[params]
  mainSections = ["posts"]
  showReadingTime = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/dan1492/"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4

[[menu.main]]
  name = "Courses"
  url = "/courses/"
  weight = 5

[[menu.main]]
  name = "Recommended Readings"
  url = "/reading/"
  weight = 6
